### ISSUE TITLE
Any chance of a default override for the edit link in the module config settings.

### ISSUE THREAD

**Issue by adrianbj** [rolandtoth/FrontEndEditLightbox#2]
I think it would be nice to not have to define it every time you call like so:

```
echo $page->feel(array('text' => 'EDIT'));
```

**Comment by rolandtoth** [comment]
Added this to the module options (unreleased).

This is how it works:
- if left empty, '#' will be used to disable empty links
- to force empty text, one should use "text" => "" in template files

**Comment by rolandtoth** [comment]
Done!
